export const TformTypes = {
  description: 'textarea',
  cuisineTypes: 'multiselect',
  tags: 'multiselect',
  phone: 'phone',
  logo: 'image',
  profile_picture: 'image',
  coverImage: 'image',
  address: 'addressSearch',
  name: 'text',
  proof_of_registration: 'file',
  proof_of_identification: 'file',
  avgPrepTime: 'number',
  minOrderAmount: 'currency',
  baseDeliveryFee: 'currency',
  commissionRate: 'number',
  first_name: 'text',
  last_name: 'text',
  email: 'email',
  date_of_birth: 'date',
  vehicle_type: 'select',
  vehicle_document: 'file',
  vehicle_plate_no: 'text',
  identification_type: 'select',
};
