/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthVerifyNowRouteImport } from './routes/auth/verify-now'
import { Route as AuthVendorSignupRouteImport } from './routes/auth/vendor-signup'
import { Route as AuthAccountVerificationRouteImport } from './routes/auth/account-verification'
import { Route as AdminDashboardHomeRouteImport } from './routes/admin-dashboard/home'
import { Route as DashboardPathlessLayoutRouteRouteImport } from './routes/dashboard/_pathlessLayout/route'
import { Route as AuthPathlessLayoutRouteRouteImport } from './routes/auth/_pathlessLayout/route'
import { Route as DashboardPathlessLayoutIndexRouteImport } from './routes/dashboard/_pathlessLayout/index'
import { Route as AuthPathlessLayoutSignupRouteImport } from './routes/auth/_pathlessLayout/signup'
import { Route as AuthPathlessLayoutLoginRouteImport } from './routes/auth/_pathlessLayout/login'
import { Route as DashboardPathlessLayoutselectStoreSelectStoreRouteImport } from './routes/dashboard/_pathlessLayout/(select-store)/select-store'
import { Route as DashboardPathlessLayoutonboardingOnboardingRouteImport } from './routes/dashboard/_pathlessLayout/(onboarding)/onboarding'
import { Route as DashboardPathlessLayoutUserIdPathlessLayoutRouteRouteImport } from './routes/dashboard/_pathlessLayout/$userId/_pathlessLayout/route'
import { Route as DashboardPathlessLayoutUserIdPathlessLayoutIndexRouteImport } from './routes/dashboard/_pathlessLayout/$userId/_pathlessLayout/index'
import { Route as DashboardPathlessLayoutUserIdPathlessLayoutvendorOrdersRouteImport } from './routes/dashboard/_pathlessLayout/$userId/_pathlessLayout/(vendor)/orders'
import { Route as DashboardPathlessLayoutUserIdPathlessLayoutdriversMyDeliveriesRouteImport } from './routes/dashboard/_pathlessLayout/$userId/_pathlessLayout/(drivers)/my-deliveries'
import { Route as DashboardPathlessLayoutUserIdPathlessLayoutcustomerOverviewRouteImport } from './routes/dashboard/_pathlessLayout/$userId/_pathlessLayout/(customer)/overview'
import { Route as DashboardPathlessLayoutUserIdPathlessLayoutcustomerMyOrdersRouteImport } from './routes/dashboard/_pathlessLayout/$userId/_pathlessLayout/(customer)/my-orders'
import { Route as DashboardPathlessLayoutUserIdPathlessLayoutcustomerExploreRouteImport } from './routes/dashboard/_pathlessLayout/$userId/_pathlessLayout/(customer)/explore'
import { Route as DashboardPathlessLayoutUserIdPathlessLayoutvendorMenuManagementIndexRouteImport } from './routes/dashboard/_pathlessLayout/$userId/_pathlessLayout/(vendor)/menu-management/index'
import { Route as DashboardPathlessLayoutUserIdPathlessLayoutvendorMenuManagementCategoriesRouteImport } from './routes/dashboard/_pathlessLayout/$userId/_pathlessLayout/(vendor)/menu-management/categories'
import { Route as DashboardPathlessLayoutUserIdPathlessLayoutcustomerTrackOrdersCheckoutIdRouteImport } from './routes/dashboard/_pathlessLayout/$userId/_pathlessLayout/(customer)/track-orders.$checkoutId'
import { Route as DashboardPathlessLayoutUserIdPathlessLayoutcustomerStoreCheckoutRouteImport } from './routes/dashboard/_pathlessLayout/$userId/_pathlessLayout/(customer)/store.checkout'
import { Route as DashboardPathlessLayoutUserIdPathlessLayoutcustomerStoreStoreSlugRouteImport } from './routes/dashboard/_pathlessLayout/$userId/_pathlessLayout/(customer)/store.$storeSlug'
import { Route as DashboardPathlessLayoutUserIdPathlessLayoutcustomerPaymentConfirmationCheckoutIdRouteImport } from './routes/dashboard/_pathlessLayout/$userId/_pathlessLayout/(customer)/payment-confirmation.$checkoutId'
import { Route as DashboardPathlessLayoutUserIdPathlessLayoutvendorMenuManagementEditItemIdRouteImport } from './routes/dashboard/_pathlessLayout/$userId/_pathlessLayout/(vendor)/menu-management/edit.$itemId'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyNowRoute = AuthVerifyNowRouteImport.update({
  id: '/verify-now',
  path: '/verify-now',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthVendorSignupRoute = AuthVendorSignupRouteImport.update({
  id: '/vendor-signup',
  path: '/vendor-signup',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthAccountVerificationRoute = AuthAccountVerificationRouteImport.update({
  id: '/account-verification',
  path: '/account-verification',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AdminDashboardHomeRoute = AdminDashboardHomeRouteImport.update({
  id: '/admin-dashboard/home',
  path: '/admin-dashboard/home',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardPathlessLayoutRouteRoute =
  DashboardPathlessLayoutRouteRouteImport.update({
    id: '/dashboard/_pathlessLayout',
    path: '/dashboard',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthPathlessLayoutRouteRoute = AuthPathlessLayoutRouteRouteImport.update({
  id: '/_pathlessLayout',
  getParentRoute: () => AuthRouteRoute,
} as any)
const DashboardPathlessLayoutIndexRoute =
  DashboardPathlessLayoutIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardPathlessLayoutRouteRoute,
  } as any)
const AuthPathlessLayoutSignupRoute =
  AuthPathlessLayoutSignupRouteImport.update({
    id: '/signup',
    path: '/signup',
    getParentRoute: () => AuthPathlessLayoutRouteRoute,
  } as any)
const AuthPathlessLayoutLoginRoute = AuthPathlessLayoutLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthPathlessLayoutRouteRoute,
} as any)
const DashboardPathlessLayoutselectStoreSelectStoreRoute =
  DashboardPathlessLayoutselectStoreSelectStoreRouteImport.update({
    id: '/(select-store)/select-store',
    path: '/select-store',
    getParentRoute: () => DashboardPathlessLayoutRouteRoute,
  } as any)
const DashboardPathlessLayoutonboardingOnboardingRoute =
  DashboardPathlessLayoutonboardingOnboardingRouteImport.update({
    id: '/(onboarding)/onboarding',
    path: '/onboarding',
    getParentRoute: () => DashboardPathlessLayoutRouteRoute,
  } as any)
const DashboardPathlessLayoutUserIdPathlessLayoutRouteRoute =
  DashboardPathlessLayoutUserIdPathlessLayoutRouteRouteImport.update({
    id: '/$userId/_pathlessLayout',
    path: '/$userId',
    getParentRoute: () => DashboardPathlessLayoutRouteRoute,
  } as any)
const DashboardPathlessLayoutUserIdPathlessLayoutIndexRoute =
  DashboardPathlessLayoutUserIdPathlessLayoutIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardPathlessLayoutUserIdPathlessLayoutRouteRoute,
  } as any)
const DashboardPathlessLayoutUserIdPathlessLayoutvendorOrdersRoute =
  DashboardPathlessLayoutUserIdPathlessLayoutvendorOrdersRouteImport.update({
    id: '/(vendor)/orders',
    path: '/orders',
    getParentRoute: () => DashboardPathlessLayoutUserIdPathlessLayoutRouteRoute,
  } as any)
const DashboardPathlessLayoutUserIdPathlessLayoutdriversMyDeliveriesRoute =
  DashboardPathlessLayoutUserIdPathlessLayoutdriversMyDeliveriesRouteImport.update(
    {
      id: '/(drivers)/my-deliveries',
      path: '/my-deliveries',
      getParentRoute: () =>
        DashboardPathlessLayoutUserIdPathlessLayoutRouteRoute,
    } as any,
  )
const DashboardPathlessLayoutUserIdPathlessLayoutcustomerOverviewRoute =
  DashboardPathlessLayoutUserIdPathlessLayoutcustomerOverviewRouteImport.update(
    {
      id: '/(customer)/overview',
      path: '/overview',
      getParentRoute: () =>
        DashboardPathlessLayoutUserIdPathlessLayoutRouteRoute,
    } as any,
  )
const DashboardPathlessLayoutUserIdPathlessLayoutcustomerMyOrdersRoute =
  DashboardPathlessLayoutUserIdPathlessLayoutcustomerMyOrdersRouteImport.update(
    {
      id: '/(customer)/my-orders',
      path: '/my-orders',
      getParentRoute: () =>
        DashboardPathlessLayoutUserIdPathlessLayoutRouteRoute,
    } as any,
  )
const DashboardPathlessLayoutUserIdPathlessLayoutcustomerExploreRoute =
  DashboardPathlessLayoutUserIdPathlessLayoutcustomerExploreRouteImport.update({
    id: '/(customer)/explore',
    path: '/explore',
    getParentRoute: () => DashboardPathlessLayoutUserIdPathlessLayoutRouteRoute,
  } as any)
const DashboardPathlessLayoutUserIdPathlessLayoutvendorMenuManagementIndexRoute =
  DashboardPathlessLayoutUserIdPathlessLayoutvendorMenuManagementIndexRouteImport.update(
    {
      id: '/(vendor)/menu-management/',
      path: '/menu-management/',
      getParentRoute: () =>
        DashboardPathlessLayoutUserIdPathlessLayoutRouteRoute,
    } as any,
  )
const DashboardPathlessLayoutUserIdPathlessLayoutvendorMenuManagementCategoriesRoute =
  DashboardPathlessLayoutUserIdPathlessLayoutvendorMenuManagementCategoriesRouteImport.update(
    {
      id: '/(vendor)/menu-management/categories',
      path: '/menu-management/categories',
      getParentRoute: () =>
        DashboardPathlessLayoutUserIdPathlessLayoutRouteRoute,
    } as any,
  )
const DashboardPathlessLayoutUserIdPathlessLayoutcustomerTrackOrdersCheckoutIdRoute =
  DashboardPathlessLayoutUserIdPathlessLayoutcustomerTrackOrdersCheckoutIdRouteImport.update(
    {
      id: '/(customer)/track-orders/$checkoutId',
      path: '/track-orders/$checkoutId',
      getParentRoute: () =>
        DashboardPathlessLayoutUserIdPathlessLayoutRouteRoute,
    } as any,
  )
const DashboardPathlessLayoutUserIdPathlessLayoutcustomerStoreCheckoutRoute =
  DashboardPathlessLayoutUserIdPathlessLayoutcustomerStoreCheckoutRouteImport.update(
    {
      id: '/(customer)/store/checkout',
      path: '/store/checkout',
      getParentRoute: () =>
        DashboardPathlessLayoutUserIdPathlessLayoutRouteRoute,
    } as any,
  )
const DashboardPathlessLayoutUserIdPathlessLayoutcustomerStoreStoreSlugRoute =
  DashboardPathlessLayoutUserIdPathlessLayoutcustomerStoreStoreSlugRouteImport.update(
    {
      id: '/(customer)/store/$storeSlug',
      path: '/store/$storeSlug',
      getParentRoute: () =>
        DashboardPathlessLayoutUserIdPathlessLayoutRouteRoute,
    } as any,
  )
const DashboardPathlessLayoutUserIdPathlessLayoutcustomerPaymentConfirmationCheckoutIdRoute =
  DashboardPathlessLayoutUserIdPathlessLayoutcustomerPaymentConfirmationCheckoutIdRouteImport.update(
    {
      id: '/(customer)/payment-confirmation/$checkoutId',
      path: '/payment-confirmation/$checkoutId',
      getParentRoute: () =>
        DashboardPathlessLayoutUserIdPathlessLayoutRouteRoute,
    } as any,
  )
const DashboardPathlessLayoutUserIdPathlessLayoutvendorMenuManagementEditItemIdRoute =
  DashboardPathlessLayoutUserIdPathlessLayoutvendorMenuManagementEditItemIdRouteImport.update(
    {
      id: '/(vendor)/menu-management/edit/$itemId',
      path: '/menu-management/edit/$itemId',
      getParentRoute: () =>
        DashboardPathlessLayoutUserIdPathlessLayoutRouteRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthPathlessLayoutRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardPathlessLayoutRouteRouteWithChildren
  '/admin-dashboard/home': typeof AdminDashboardHomeRoute
  '/auth/account-verification': typeof AuthAccountVerificationRoute
  '/auth/vendor-signup': typeof AuthVendorSignupRoute
  '/auth/verify-now': typeof AuthVerifyNowRoute
  '/auth/login': typeof AuthPathlessLayoutLoginRoute
  '/auth/signup': typeof AuthPathlessLayoutSignupRoute
  '/dashboard/': typeof DashboardPathlessLayoutIndexRoute
  '/dashboard/$userId': typeof DashboardPathlessLayoutUserIdPathlessLayoutRouteRouteWithChildren
  '/dashboard/onboarding': typeof DashboardPathlessLayoutonboardingOnboardingRoute
  '/dashboard/select-store': typeof DashboardPathlessLayoutselectStoreSelectStoreRoute
  '/dashboard/$userId/': typeof DashboardPathlessLayoutUserIdPathlessLayoutIndexRoute
  '/dashboard/$userId/explore': typeof DashboardPathlessLayoutUserIdPathlessLayoutcustomerExploreRoute
  '/dashboard/$userId/my-orders': typeof DashboardPathlessLayoutUserIdPathlessLayoutcustomerMyOrdersRoute
  '/dashboard/$userId/overview': typeof DashboardPathlessLayoutUserIdPathlessLayoutcustomerOverviewRoute
  '/dashboard/$userId/my-deliveries': typeof DashboardPathlessLayoutUserIdPathlessLayoutdriversMyDeliveriesRoute
  '/dashboard/$userId/orders': typeof DashboardPathlessLayoutUserIdPathlessLayoutvendorOrdersRoute
  '/dashboard/$userId/payment-confirmation/$checkoutId': typeof DashboardPathlessLayoutUserIdPathlessLayoutcustomerPaymentConfirmationCheckoutIdRoute
  '/dashboard/$userId/store/$storeSlug': typeof DashboardPathlessLayoutUserIdPathlessLayoutcustomerStoreStoreSlugRoute
  '/dashboard/$userId/store/checkout': typeof DashboardPathlessLayoutUserIdPathlessLayoutcustomerStoreCheckoutRoute
  '/dashboard/$userId/track-orders/$checkoutId': typeof DashboardPathlessLayoutUserIdPathlessLayoutcustomerTrackOrdersCheckoutIdRoute
  '/dashboard/$userId/menu-management/categories': typeof DashboardPathlessLayoutUserIdPathlessLayoutvendorMenuManagementCategoriesRoute
  '/dashboard/$userId/menu-management/': typeof DashboardPathlessLayoutUserIdPathlessLayoutvendorMenuManagementIndexRoute
  '/dashboard/$userId/menu-management/edit/$itemId': typeof DashboardPathlessLayoutUserIdPathlessLayoutvendorMenuManagementEditItemIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthPathlessLayoutRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/admin-dashboard/home': typeof AdminDashboardHomeRoute
  '/auth/account-verification': typeof AuthAccountVerificationRoute
  '/auth/vendor-signup': typeof AuthVendorSignupRoute
  '/auth/verify-now': typeof AuthVerifyNowRoute
  '/auth/login': typeof AuthPathlessLayoutLoginRoute
  '/auth/signup': typeof AuthPathlessLayoutSignupRoute
  '/dashboard': typeof DashboardPathlessLayoutIndexRoute
  '/dashboard/onboarding': typeof DashboardPathlessLayoutonboardingOnboardingRoute
  '/dashboard/select-store': typeof DashboardPathlessLayoutselectStoreSelectStoreRoute
  '/dashboard/$userId': typeof DashboardPathlessLayoutUserIdPathlessLayoutIndexRoute
  '/dashboard/$userId/explore': typeof DashboardPathlessLayoutUserIdPathlessLayoutcustomerExploreRoute
  '/dashboard/$userId/my-orders': typeof DashboardPathlessLayoutUserIdPathlessLayoutcustomerMyOrdersRoute
  '/dashboard/$userId/overview': typeof DashboardPathlessLayoutUserIdPathlessLayoutcustomerOverviewRoute
  '/dashboard/$userId/my-deliveries': typeof DashboardPathlessLayoutUserIdPathlessLayoutdriversMyDeliveriesRoute
  '/dashboard/$userId/orders': typeof DashboardPathlessLayoutUserIdPathlessLayoutvendorOrdersRoute
  '/dashboard/$userId/payment-confirmation/$checkoutId': typeof DashboardPathlessLayoutUserIdPathlessLayoutcustomerPaymentConfirmationCheckoutIdRoute
  '/dashboard/$userId/store/$storeSlug': typeof DashboardPathlessLayoutUserIdPathlessLayoutcustomerStoreStoreSlugRoute
  '/dashboard/$userId/store/checkout': typeof DashboardPathlessLayoutUserIdPathlessLayoutcustomerStoreCheckoutRoute
  '/dashboard/$userId/track-orders/$checkoutId': typeof DashboardPathlessLayoutUserIdPathlessLayoutcustomerTrackOrdersCheckoutIdRoute
  '/dashboard/$userId/menu-management/categories': typeof DashboardPathlessLayoutUserIdPathlessLayoutvendorMenuManagementCategoriesRoute
  '/dashboard/$userId/menu-management': typeof DashboardPathlessLayoutUserIdPathlessLayoutvendorMenuManagementIndexRoute
  '/dashboard/$userId/menu-management/edit/$itemId': typeof DashboardPathlessLayoutUserIdPathlessLayoutvendorMenuManagementEditItemIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth/_pathlessLayout': typeof AuthPathlessLayoutRouteRouteWithChildren
  '/dashboard/_pathlessLayout': typeof DashboardPathlessLayoutRouteRouteWithChildren
  '/admin-dashboard/home': typeof AdminDashboardHomeRoute
  '/auth/account-verification': typeof AuthAccountVerificationRoute
  '/auth/vendor-signup': typeof AuthVendorSignupRoute
  '/auth/verify-now': typeof AuthVerifyNowRoute
  '/auth/_pathlessLayout/login': typeof AuthPathlessLayoutLoginRoute
  '/auth/_pathlessLayout/signup': typeof AuthPathlessLayoutSignupRoute
  '/dashboard/_pathlessLayout/': typeof DashboardPathlessLayoutIndexRoute
  '/dashboard/_pathlessLayout/$userId/_pathlessLayout': typeof DashboardPathlessLayoutUserIdPathlessLayoutRouteRouteWithChildren
  '/dashboard/_pathlessLayout/(onboarding)/onboarding': typeof DashboardPathlessLayoutonboardingOnboardingRoute
  '/dashboard/_pathlessLayout/(select-store)/select-store': typeof DashboardPathlessLayoutselectStoreSelectStoreRoute
  '/dashboard/_pathlessLayout/$userId/_pathlessLayout/': typeof DashboardPathlessLayoutUserIdPathlessLayoutIndexRoute
  '/dashboard/_pathlessLayout/$userId/_pathlessLayout/(customer)/explore': typeof DashboardPathlessLayoutUserIdPathlessLayoutcustomerExploreRoute
  '/dashboard/_pathlessLayout/$userId/_pathlessLayout/(customer)/my-orders': typeof DashboardPathlessLayoutUserIdPathlessLayoutcustomerMyOrdersRoute
  '/dashboard/_pathlessLayout/$userId/_pathlessLayout/(customer)/overview': typeof DashboardPathlessLayoutUserIdPathlessLayoutcustomerOverviewRoute
  '/dashboard/_pathlessLayout/$userId/_pathlessLayout/(drivers)/my-deliveries': typeof DashboardPathlessLayoutUserIdPathlessLayoutdriversMyDeliveriesRoute
  '/dashboard/_pathlessLayout/$userId/_pathlessLayout/(vendor)/orders': typeof DashboardPathlessLayoutUserIdPathlessLayoutvendorOrdersRoute
  '/dashboard/_pathlessLayout/$userId/_pathlessLayout/(customer)/payment-confirmation/$checkoutId': typeof DashboardPathlessLayoutUserIdPathlessLayoutcustomerPaymentConfirmationCheckoutIdRoute
  '/dashboard/_pathlessLayout/$userId/_pathlessLayout/(customer)/store/$storeSlug': typeof DashboardPathlessLayoutUserIdPathlessLayoutcustomerStoreStoreSlugRoute
  '/dashboard/_pathlessLayout/$userId/_pathlessLayout/(customer)/store/checkout': typeof DashboardPathlessLayoutUserIdPathlessLayoutcustomerStoreCheckoutRoute
  '/dashboard/_pathlessLayout/$userId/_pathlessLayout/(customer)/track-orders/$checkoutId': typeof DashboardPathlessLayoutUserIdPathlessLayoutcustomerTrackOrdersCheckoutIdRoute
  '/dashboard/_pathlessLayout/$userId/_pathlessLayout/(vendor)/menu-management/categories': typeof DashboardPathlessLayoutUserIdPathlessLayoutvendorMenuManagementCategoriesRoute
  '/dashboard/_pathlessLayout/$userId/_pathlessLayout/(vendor)/menu-management/': typeof DashboardPathlessLayoutUserIdPathlessLayoutvendorMenuManagementIndexRoute
  '/dashboard/_pathlessLayout/$userId/_pathlessLayout/(vendor)/menu-management/edit/$itemId': typeof DashboardPathlessLayoutUserIdPathlessLayoutvendorMenuManagementEditItemIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/about'
    | '/dashboard'
    | '/admin-dashboard/home'
    | '/auth/account-verification'
    | '/auth/vendor-signup'
    | '/auth/verify-now'
    | '/auth/login'
    | '/auth/signup'
    | '/dashboard/'
    | '/dashboard/$userId'
    | '/dashboard/onboarding'
    | '/dashboard/select-store'
    | '/dashboard/$userId/'
    | '/dashboard/$userId/explore'
    | '/dashboard/$userId/my-orders'
    | '/dashboard/$userId/overview'
    | '/dashboard/$userId/my-deliveries'
    | '/dashboard/$userId/orders'
    | '/dashboard/$userId/payment-confirmation/$checkoutId'
    | '/dashboard/$userId/store/$storeSlug'
    | '/dashboard/$userId/store/checkout'
    | '/dashboard/$userId/track-orders/$checkoutId'
    | '/dashboard/$userId/menu-management/categories'
    | '/dashboard/$userId/menu-management/'
    | '/dashboard/$userId/menu-management/edit/$itemId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/about'
    | '/admin-dashboard/home'
    | '/auth/account-verification'
    | '/auth/vendor-signup'
    | '/auth/verify-now'
    | '/auth/login'
    | '/auth/signup'
    | '/dashboard'
    | '/dashboard/onboarding'
    | '/dashboard/select-store'
    | '/dashboard/$userId'
    | '/dashboard/$userId/explore'
    | '/dashboard/$userId/my-orders'
    | '/dashboard/$userId/overview'
    | '/dashboard/$userId/my-deliveries'
    | '/dashboard/$userId/orders'
    | '/dashboard/$userId/payment-confirmation/$checkoutId'
    | '/dashboard/$userId/store/$storeSlug'
    | '/dashboard/$userId/store/checkout'
    | '/dashboard/$userId/track-orders/$checkoutId'
    | '/dashboard/$userId/menu-management/categories'
    | '/dashboard/$userId/menu-management'
    | '/dashboard/$userId/menu-management/edit/$itemId'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/about'
    | '/auth/_pathlessLayout'
    | '/dashboard/_pathlessLayout'
    | '/admin-dashboard/home'
    | '/auth/account-verification'
    | '/auth/vendor-signup'
    | '/auth/verify-now'
    | '/auth/_pathlessLayout/login'
    | '/auth/_pathlessLayout/signup'
    | '/dashboard/_pathlessLayout/'
    | '/dashboard/_pathlessLayout/$userId/_pathlessLayout'
    | '/dashboard/_pathlessLayout/(onboarding)/onboarding'
    | '/dashboard/_pathlessLayout/(select-store)/select-store'
    | '/dashboard/_pathlessLayout/$userId/_pathlessLayout/'
    | '/dashboard/_pathlessLayout/$userId/_pathlessLayout/(customer)/explore'
    | '/dashboard/_pathlessLayout/$userId/_pathlessLayout/(customer)/my-orders'
    | '/dashboard/_pathlessLayout/$userId/_pathlessLayout/(customer)/overview'
    | '/dashboard/_pathlessLayout/$userId/_pathlessLayout/(drivers)/my-deliveries'
    | '/dashboard/_pathlessLayout/$userId/_pathlessLayout/(vendor)/orders'
    | '/dashboard/_pathlessLayout/$userId/_pathlessLayout/(customer)/payment-confirmation/$checkoutId'
    | '/dashboard/_pathlessLayout/$userId/_pathlessLayout/(customer)/store/$storeSlug'
    | '/dashboard/_pathlessLayout/$userId/_pathlessLayout/(customer)/store/checkout'
    | '/dashboard/_pathlessLayout/$userId/_pathlessLayout/(customer)/track-orders/$checkoutId'
    | '/dashboard/_pathlessLayout/$userId/_pathlessLayout/(vendor)/menu-management/categories'
    | '/dashboard/_pathlessLayout/$userId/_pathlessLayout/(vendor)/menu-management/'
    | '/dashboard/_pathlessLayout/$userId/_pathlessLayout/(vendor)/menu-management/edit/$itemId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  DashboardPathlessLayoutRouteRoute: typeof DashboardPathlessLayoutRouteRouteWithChildren
  AdminDashboardHomeRoute: typeof AdminDashboardHomeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify-now': {
      id: '/auth/verify-now'
      path: '/verify-now'
      fullPath: '/auth/verify-now'
      preLoaderRoute: typeof AuthVerifyNowRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/vendor-signup': {
      id: '/auth/vendor-signup'
      path: '/vendor-signup'
      fullPath: '/auth/vendor-signup'
      preLoaderRoute: typeof AuthVendorSignupRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/account-verification': {
      id: '/auth/account-verification'
      path: '/account-verification'
      fullPath: '/auth/account-verification'
      preLoaderRoute: typeof AuthAccountVerificationRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/admin-dashboard/home': {
      id: '/admin-dashboard/home'
      path: '/admin-dashboard/home'
      fullPath: '/admin-dashboard/home'
      preLoaderRoute: typeof AdminDashboardHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/_pathlessLayout': {
      id: '/dashboard/_pathlessLayout'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardPathlessLayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/_pathlessLayout': {
      id: '/auth/_pathlessLayout'
      path: ''
      fullPath: '/auth'
      preLoaderRoute: typeof AuthPathlessLayoutRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/dashboard/_pathlessLayout/': {
      id: '/dashboard/_pathlessLayout/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardPathlessLayoutIndexRouteImport
      parentRoute: typeof DashboardPathlessLayoutRouteRoute
    }
    '/auth/_pathlessLayout/signup': {
      id: '/auth/_pathlessLayout/signup'
      path: '/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthPathlessLayoutSignupRouteImport
      parentRoute: typeof AuthPathlessLayoutRouteRoute
    }
    '/auth/_pathlessLayout/login': {
      id: '/auth/_pathlessLayout/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthPathlessLayoutLoginRouteImport
      parentRoute: typeof AuthPathlessLayoutRouteRoute
    }
    '/dashboard/_pathlessLayout/(select-store)/select-store': {
      id: '/dashboard/_pathlessLayout/(select-store)/select-store'
      path: '/select-store'
      fullPath: '/dashboard/select-store'
      preLoaderRoute: typeof DashboardPathlessLayoutselectStoreSelectStoreRouteImport
      parentRoute: typeof DashboardPathlessLayoutRouteRoute
    }
    '/dashboard/_pathlessLayout/(onboarding)/onboarding': {
      id: '/dashboard/_pathlessLayout/(onboarding)/onboarding'
      path: '/onboarding'
      fullPath: '/dashboard/onboarding'
      preLoaderRoute: typeof DashboardPathlessLayoutonboardingOnboardingRouteImport
      parentRoute: typeof DashboardPathlessLayoutRouteRoute
    }
    '/dashboard/_pathlessLayout/$userId/_pathlessLayout': {
      id: '/dashboard/_pathlessLayout/$userId/_pathlessLayout'
      path: '/$userId'
      fullPath: '/dashboard/$userId'
      preLoaderRoute: typeof DashboardPathlessLayoutUserIdPathlessLayoutRouteRouteImport
      parentRoute: typeof DashboardPathlessLayoutRouteRoute
    }
    '/dashboard/_pathlessLayout/$userId/_pathlessLayout/': {
      id: '/dashboard/_pathlessLayout/$userId/_pathlessLayout/'
      path: '/'
      fullPath: '/dashboard/$userId/'
      preLoaderRoute: typeof DashboardPathlessLayoutUserIdPathlessLayoutIndexRouteImport
      parentRoute: typeof DashboardPathlessLayoutUserIdPathlessLayoutRouteRoute
    }
    '/dashboard/_pathlessLayout/$userId/_pathlessLayout/(vendor)/orders': {
      id: '/dashboard/_pathlessLayout/$userId/_pathlessLayout/(vendor)/orders'
      path: '/orders'
      fullPath: '/dashboard/$userId/orders'
      preLoaderRoute: typeof DashboardPathlessLayoutUserIdPathlessLayoutvendorOrdersRouteImport
      parentRoute: typeof DashboardPathlessLayoutUserIdPathlessLayoutRouteRoute
    }
    '/dashboard/_pathlessLayout/$userId/_pathlessLayout/(drivers)/my-deliveries': {
      id: '/dashboard/_pathlessLayout/$userId/_pathlessLayout/(drivers)/my-deliveries'
      path: '/my-deliveries'
      fullPath: '/dashboard/$userId/my-deliveries'
      preLoaderRoute: typeof DashboardPathlessLayoutUserIdPathlessLayoutdriversMyDeliveriesRouteImport
      parentRoute: typeof DashboardPathlessLayoutUserIdPathlessLayoutRouteRoute
    }
    '/dashboard/_pathlessLayout/$userId/_pathlessLayout/(customer)/overview': {
      id: '/dashboard/_pathlessLayout/$userId/_pathlessLayout/(customer)/overview'
      path: '/overview'
      fullPath: '/dashboard/$userId/overview'
      preLoaderRoute: typeof DashboardPathlessLayoutUserIdPathlessLayoutcustomerOverviewRouteImport
      parentRoute: typeof DashboardPathlessLayoutUserIdPathlessLayoutRouteRoute
    }
    '/dashboard/_pathlessLayout/$userId/_pathlessLayout/(customer)/my-orders': {
      id: '/dashboard/_pathlessLayout/$userId/_pathlessLayout/(customer)/my-orders'
      path: '/my-orders'
      fullPath: '/dashboard/$userId/my-orders'
      preLoaderRoute: typeof DashboardPathlessLayoutUserIdPathlessLayoutcustomerMyOrdersRouteImport
      parentRoute: typeof DashboardPathlessLayoutUserIdPathlessLayoutRouteRoute
    }
    '/dashboard/_pathlessLayout/$userId/_pathlessLayout/(customer)/explore': {
      id: '/dashboard/_pathlessLayout/$userId/_pathlessLayout/(customer)/explore'
      path: '/explore'
      fullPath: '/dashboard/$userId/explore'
      preLoaderRoute: typeof DashboardPathlessLayoutUserIdPathlessLayoutcustomerExploreRouteImport
      parentRoute: typeof DashboardPathlessLayoutUserIdPathlessLayoutRouteRoute
    }
    '/dashboard/_pathlessLayout/$userId/_pathlessLayout/(vendor)/menu-management/': {
      id: '/dashboard/_pathlessLayout/$userId/_pathlessLayout/(vendor)/menu-management/'
      path: '/menu-management'
      fullPath: '/dashboard/$userId/menu-management/'
      preLoaderRoute: typeof DashboardPathlessLayoutUserIdPathlessLayoutvendorMenuManagementIndexRouteImport
      parentRoute: typeof DashboardPathlessLayoutUserIdPathlessLayoutRouteRoute
    }
    '/dashboard/_pathlessLayout/$userId/_pathlessLayout/(vendor)/menu-management/categories': {
      id: '/dashboard/_pathlessLayout/$userId/_pathlessLayout/(vendor)/menu-management/categories'
      path: '/menu-management/categories'
      fullPath: '/dashboard/$userId/menu-management/categories'
      preLoaderRoute: typeof DashboardPathlessLayoutUserIdPathlessLayoutvendorMenuManagementCategoriesRouteImport
      parentRoute: typeof DashboardPathlessLayoutUserIdPathlessLayoutRouteRoute
    }
    '/dashboard/_pathlessLayout/$userId/_pathlessLayout/(customer)/track-orders/$checkoutId': {
      id: '/dashboard/_pathlessLayout/$userId/_pathlessLayout/(customer)/track-orders/$checkoutId'
      path: '/track-orders/$checkoutId'
      fullPath: '/dashboard/$userId/track-orders/$checkoutId'
      preLoaderRoute: typeof DashboardPathlessLayoutUserIdPathlessLayoutcustomerTrackOrdersCheckoutIdRouteImport
      parentRoute: typeof DashboardPathlessLayoutUserIdPathlessLayoutRouteRoute
    }
    '/dashboard/_pathlessLayout/$userId/_pathlessLayout/(customer)/store/checkout': {
      id: '/dashboard/_pathlessLayout/$userId/_pathlessLayout/(customer)/store/checkout'
      path: '/store/checkout'
      fullPath: '/dashboard/$userId/store/checkout'
      preLoaderRoute: typeof DashboardPathlessLayoutUserIdPathlessLayoutcustomerStoreCheckoutRouteImport
      parentRoute: typeof DashboardPathlessLayoutUserIdPathlessLayoutRouteRoute
    }
    '/dashboard/_pathlessLayout/$userId/_pathlessLayout/(customer)/store/$storeSlug': {
      id: '/dashboard/_pathlessLayout/$userId/_pathlessLayout/(customer)/store/$storeSlug'
      path: '/store/$storeSlug'
      fullPath: '/dashboard/$userId/store/$storeSlug'
      preLoaderRoute: typeof DashboardPathlessLayoutUserIdPathlessLayoutcustomerStoreStoreSlugRouteImport
      parentRoute: typeof DashboardPathlessLayoutUserIdPathlessLayoutRouteRoute
    }
    '/dashboard/_pathlessLayout/$userId/_pathlessLayout/(customer)/payment-confirmation/$checkoutId': {
      id: '/dashboard/_pathlessLayout/$userId/_pathlessLayout/(customer)/payment-confirmation/$checkoutId'
      path: '/payment-confirmation/$checkoutId'
      fullPath: '/dashboard/$userId/payment-confirmation/$checkoutId'
      preLoaderRoute: typeof DashboardPathlessLayoutUserIdPathlessLayoutcustomerPaymentConfirmationCheckoutIdRouteImport
      parentRoute: typeof DashboardPathlessLayoutUserIdPathlessLayoutRouteRoute
    }
    '/dashboard/_pathlessLayout/$userId/_pathlessLayout/(vendor)/menu-management/edit/$itemId': {
      id: '/dashboard/_pathlessLayout/$userId/_pathlessLayout/(vendor)/menu-management/edit/$itemId'
      path: '/menu-management/edit/$itemId'
      fullPath: '/dashboard/$userId/menu-management/edit/$itemId'
      preLoaderRoute: typeof DashboardPathlessLayoutUserIdPathlessLayoutvendorMenuManagementEditItemIdRouteImport
      parentRoute: typeof DashboardPathlessLayoutUserIdPathlessLayoutRouteRoute
    }
  }
}

interface AuthPathlessLayoutRouteRouteChildren {
  AuthPathlessLayoutLoginRoute: typeof AuthPathlessLayoutLoginRoute
  AuthPathlessLayoutSignupRoute: typeof AuthPathlessLayoutSignupRoute
}

const AuthPathlessLayoutRouteRouteChildren: AuthPathlessLayoutRouteRouteChildren =
  {
    AuthPathlessLayoutLoginRoute: AuthPathlessLayoutLoginRoute,
    AuthPathlessLayoutSignupRoute: AuthPathlessLayoutSignupRoute,
  }

const AuthPathlessLayoutRouteRouteWithChildren =
  AuthPathlessLayoutRouteRoute._addFileChildren(
    AuthPathlessLayoutRouteRouteChildren,
  )

interface AuthRouteRouteChildren {
  AuthPathlessLayoutRouteRoute: typeof AuthPathlessLayoutRouteRouteWithChildren
  AuthAccountVerificationRoute: typeof AuthAccountVerificationRoute
  AuthVendorSignupRoute: typeof AuthVendorSignupRoute
  AuthVerifyNowRoute: typeof AuthVerifyNowRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthPathlessLayoutRouteRoute: AuthPathlessLayoutRouteRouteWithChildren,
  AuthAccountVerificationRoute: AuthAccountVerificationRoute,
  AuthVendorSignupRoute: AuthVendorSignupRoute,
  AuthVerifyNowRoute: AuthVerifyNowRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface DashboardPathlessLayoutUserIdPathlessLayoutRouteRouteChildren {
  DashboardPathlessLayoutUserIdPathlessLayoutIndexRoute: typeof DashboardPathlessLayoutUserIdPathlessLayoutIndexRoute
  DashboardPathlessLayoutUserIdPathlessLayoutcustomerExploreRoute: typeof DashboardPathlessLayoutUserIdPathlessLayoutcustomerExploreRoute
  DashboardPathlessLayoutUserIdPathlessLayoutcustomerMyOrdersRoute: typeof DashboardPathlessLayoutUserIdPathlessLayoutcustomerMyOrdersRoute
  DashboardPathlessLayoutUserIdPathlessLayoutcustomerOverviewRoute: typeof DashboardPathlessLayoutUserIdPathlessLayoutcustomerOverviewRoute
  DashboardPathlessLayoutUserIdPathlessLayoutdriversMyDeliveriesRoute: typeof DashboardPathlessLayoutUserIdPathlessLayoutdriversMyDeliveriesRoute
  DashboardPathlessLayoutUserIdPathlessLayoutvendorOrdersRoute: typeof DashboardPathlessLayoutUserIdPathlessLayoutvendorOrdersRoute
  DashboardPathlessLayoutUserIdPathlessLayoutcustomerPaymentConfirmationCheckoutIdRoute: typeof DashboardPathlessLayoutUserIdPathlessLayoutcustomerPaymentConfirmationCheckoutIdRoute
  DashboardPathlessLayoutUserIdPathlessLayoutcustomerStoreStoreSlugRoute: typeof DashboardPathlessLayoutUserIdPathlessLayoutcustomerStoreStoreSlugRoute
  DashboardPathlessLayoutUserIdPathlessLayoutcustomerStoreCheckoutRoute: typeof DashboardPathlessLayoutUserIdPathlessLayoutcustomerStoreCheckoutRoute
  DashboardPathlessLayoutUserIdPathlessLayoutcustomerTrackOrdersCheckoutIdRoute: typeof DashboardPathlessLayoutUserIdPathlessLayoutcustomerTrackOrdersCheckoutIdRoute
  DashboardPathlessLayoutUserIdPathlessLayoutvendorMenuManagementCategoriesRoute: typeof DashboardPathlessLayoutUserIdPathlessLayoutvendorMenuManagementCategoriesRoute
  DashboardPathlessLayoutUserIdPathlessLayoutvendorMenuManagementIndexRoute: typeof DashboardPathlessLayoutUserIdPathlessLayoutvendorMenuManagementIndexRoute
  DashboardPathlessLayoutUserIdPathlessLayoutvendorMenuManagementEditItemIdRoute: typeof DashboardPathlessLayoutUserIdPathlessLayoutvendorMenuManagementEditItemIdRoute
}

const DashboardPathlessLayoutUserIdPathlessLayoutRouteRouteChildren: DashboardPathlessLayoutUserIdPathlessLayoutRouteRouteChildren =
  {
    DashboardPathlessLayoutUserIdPathlessLayoutIndexRoute:
      DashboardPathlessLayoutUserIdPathlessLayoutIndexRoute,
    DashboardPathlessLayoutUserIdPathlessLayoutcustomerExploreRoute:
      DashboardPathlessLayoutUserIdPathlessLayoutcustomerExploreRoute,
    DashboardPathlessLayoutUserIdPathlessLayoutcustomerMyOrdersRoute:
      DashboardPathlessLayoutUserIdPathlessLayoutcustomerMyOrdersRoute,
    DashboardPathlessLayoutUserIdPathlessLayoutcustomerOverviewRoute:
      DashboardPathlessLayoutUserIdPathlessLayoutcustomerOverviewRoute,
    DashboardPathlessLayoutUserIdPathlessLayoutdriversMyDeliveriesRoute:
      DashboardPathlessLayoutUserIdPathlessLayoutdriversMyDeliveriesRoute,
    DashboardPathlessLayoutUserIdPathlessLayoutvendorOrdersRoute:
      DashboardPathlessLayoutUserIdPathlessLayoutvendorOrdersRoute,
    DashboardPathlessLayoutUserIdPathlessLayoutcustomerPaymentConfirmationCheckoutIdRoute:
      DashboardPathlessLayoutUserIdPathlessLayoutcustomerPaymentConfirmationCheckoutIdRoute,
    DashboardPathlessLayoutUserIdPathlessLayoutcustomerStoreStoreSlugRoute:
      DashboardPathlessLayoutUserIdPathlessLayoutcustomerStoreStoreSlugRoute,
    DashboardPathlessLayoutUserIdPathlessLayoutcustomerStoreCheckoutRoute:
      DashboardPathlessLayoutUserIdPathlessLayoutcustomerStoreCheckoutRoute,
    DashboardPathlessLayoutUserIdPathlessLayoutcustomerTrackOrdersCheckoutIdRoute:
      DashboardPathlessLayoutUserIdPathlessLayoutcustomerTrackOrdersCheckoutIdRoute,
    DashboardPathlessLayoutUserIdPathlessLayoutvendorMenuManagementCategoriesRoute:
      DashboardPathlessLayoutUserIdPathlessLayoutvendorMenuManagementCategoriesRoute,
    DashboardPathlessLayoutUserIdPathlessLayoutvendorMenuManagementIndexRoute:
      DashboardPathlessLayoutUserIdPathlessLayoutvendorMenuManagementIndexRoute,
    DashboardPathlessLayoutUserIdPathlessLayoutvendorMenuManagementEditItemIdRoute:
      DashboardPathlessLayoutUserIdPathlessLayoutvendorMenuManagementEditItemIdRoute,
  }

const DashboardPathlessLayoutUserIdPathlessLayoutRouteRouteWithChildren =
  DashboardPathlessLayoutUserIdPathlessLayoutRouteRoute._addFileChildren(
    DashboardPathlessLayoutUserIdPathlessLayoutRouteRouteChildren,
  )

interface DashboardPathlessLayoutRouteRouteChildren {
  DashboardPathlessLayoutIndexRoute: typeof DashboardPathlessLayoutIndexRoute
  DashboardPathlessLayoutUserIdPathlessLayoutRouteRoute: typeof DashboardPathlessLayoutUserIdPathlessLayoutRouteRouteWithChildren
  DashboardPathlessLayoutonboardingOnboardingRoute: typeof DashboardPathlessLayoutonboardingOnboardingRoute
  DashboardPathlessLayoutselectStoreSelectStoreRoute: typeof DashboardPathlessLayoutselectStoreSelectStoreRoute
}

const DashboardPathlessLayoutRouteRouteChildren: DashboardPathlessLayoutRouteRouteChildren =
  {
    DashboardPathlessLayoutIndexRoute: DashboardPathlessLayoutIndexRoute,
    DashboardPathlessLayoutUserIdPathlessLayoutRouteRoute:
      DashboardPathlessLayoutUserIdPathlessLayoutRouteRouteWithChildren,
    DashboardPathlessLayoutonboardingOnboardingRoute:
      DashboardPathlessLayoutonboardingOnboardingRoute,
    DashboardPathlessLayoutselectStoreSelectStoreRoute:
      DashboardPathlessLayoutselectStoreSelectStoreRoute,
  }

const DashboardPathlessLayoutRouteRouteWithChildren =
  DashboardPathlessLayoutRouteRoute._addFileChildren(
    DashboardPathlessLayoutRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  DashboardPathlessLayoutRouteRoute:
    DashboardPathlessLayoutRouteRouteWithChildren,
  AdminDashboardHomeRoute: AdminDashboardHomeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
